version: 2

.php70: &php70
    environment:
        PHP_VERSION: "7.0"

.php71: &php71
    environment:
        PHP_VERSION: "7.1"

.php72: &php72
    environment:
        PHP_VERSION: "7.2"

.php73: &php73
    environment:
        PHP_VERSION: "7.3"

.build_job_template: &build_job_template
        machine:
            enabled: true
            docker_layer_caching: false
        steps:
            - checkout
            - run:
                command: |
                    make build PHP_VERSION=$PHP_VERSION
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    docker push kolemp/docker-php-nginx:$PHP_VERSION
                    if [ "$PHP_VERSION" == "7.3" ]; then
                        docker tag kolemp/docker-php-nginx:$PHP_VERSION kolemp/docker-php-nginx:latest
                        docker push kolemp/docker-php-nginx:latest
                    fi

jobs:
    build_70:
        <<: *php70
        <<: *build_job_template
    build_71:
        <<: *php71
        <<: *build_job_template
    build_72:
        <<: *php72
        <<: *build_job_template
    build_73:
        <<: *php73
        <<: *build_job_template

workflows:
  version: 2
  build_and_push:
      jobs:
          - build_70:
              filters:
                  branches:
                      only: master
          - build_71:
              filters:
                  branches:
                      only: master
          - build_72:
              filters:
                  branches:
                      only: master
          - build_73:
              filters:
                  branches:
                      only: master
