version: 2

.php70: &php70
    environment:
        PHP_VERSION: "7.0"

.php71: &php71
    environment:
        PHP_VERSION: "7.1"

.php72: &php72
    environment:
        PHP_VERSION: "7.2"

.php70_rsyslog: &php70_rsyslog
    environment:
        PHP_VERSION: "7.0"
        WITH_RSYSLOG: "true"

.php71_rsyslog: &php71_rsyslog
    environment:
        PHP_VERSION: "7.1"
        WITH_RSYSLOG: "true"

.php72_rsyslog: &php72_rsyslog
    environment:
        PHP_VERSION: "7.2"
        WITH_RSYSLOG: "true"

.build_job_template: &build_job_template
        machine:
            enabled: true
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                command: |
                    make build PHP_VERSION=$PHP_VERSION WITH_RSYSLOG=$WITH_RSYSLOG
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    if [ "$WITH_RSYSLOG" != "true" ]; then
                        docker push kolemp/docker-php-nginx:$PHP_VERSION
                    else
                        docker push kolemp/docker-php-nginx:$PHP_VERSION-rsyslog
                    fi

                    if [ "$PHP_VERSION" == "7.2" ] && [ "$WITH_RSYSLOG" != "true" ]; then
                        docker tag kolemp/docker-php-nginx:$PHP_VERSION kolemp/docker-php-nginx:latest
                        docker push kolemp/docker-php-nginx:latest
                    fi

jobs:
    build_70:
        <<: *php70
        <<: *build_job_template
    build_71:
        <<: *php71
        <<: *build_job_template
    build_72:
        <<: *php72
        <<: *build_job_template
    build_70_rsyslog:
        <<: *php70_rsyslog
        <<: *build_job_template
    build_71_rsyslog:
        <<: *php71_rsyslog
        <<: *build_job_template
    build_72_rsyslog:
        <<: *php72_rsyslog
        <<: *build_job_template

workflows:
  version: 2
  build_and_push:
      jobs:
          - build_70:
              filters:
                  branches:
                      only: master
          - build_71:
              filters:
                  branches:
                      only: master
          - build_72:
              filters:
                  branches:
                      only: master
          - build_70_rsyslog
          - build_71_rsyslog
          - build_72_rsyslog
